#ifndef _BRIDGESERVER_PRECOMPILED_HEADER_H_CUSTOM
#define _BRIDGESERVER_PRECOMPILED_HEADER_H_CUSTOM

#ifdef _MSC_VER
#pragma once
#endif

/* -- Put your custom code here -- */

#endif // _BRIDGESERVER_PRECOMPILED_HEADER_H_CUSTOM
